language: go

go:
- 1.13.x
- 1.14.x

go_import_path: github.com/liggitt/clientgofix

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

script:
- make build test fmt lint vet
